language: csharp
mono: none
dotnet: 2.1.502
script:
 - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
 - dotnet restore
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - ./tools/csmacnz.Coveralls -i ./CoverTest.Tests/coverage.opencover.xml  --repoToken $COVERALLS_REPO_TOKEN --opencover

